# This file is part of vitrine.
# https://github.com/globocom/vitrine

# Licensed under the MIT license:
# http://www.opensource.org/licenses/MIT-license
# Copyright (c) 2015, Globo.com <talentos@corp.globo.com>

language: python

python:
    - "2.7"
    - "3.4"

install:
    # install python requirements
    - make setup

script:
    # run tests
    - make test
