hooks:
    build:
        - touch /home/application/current/vitrine/config/local.conf
        - sudo locale-gen pt_BR.UTF-8 en_US.UTF-8
        - export LC_ALL=pt_BR.UTF-8
        - export LANG=pt_BR.UTF-8
